version: '3.7'
services:
  ngx_small_light:
    container_name: ngx_small_light
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085" 
      - "8084:8084"
    volumes:
      - ./logs:/ngx_small_light/logs:rw